# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\rvad.bridge.v1\"d\n\x08MicChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\x12\x10\n\x08is_begin\x18\x04 \x01(\x08\x12\x0e\n\x06is_end\x18\x05 \x01(\x08\"R\n\x08VadEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\x10\n\x08is_begin\x18\x03 \x01(\x08\x12\x0e\n\x06is_end\x18\x04 \x01(\x08\x32P\n\x0b\x41udioBridge\x12\x41\n\tStreamMic\x12\x17.vad.bridge.v1.MicChunk\x1a\x17.vad.bridge.v1.VadEvent(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MICCHUNK']._serialized_start=31
  _globals['_MICCHUNK']._serialized_end=131
  _globals['_VADEVENT']._serialized_start=133
  _globals['_VADEVENT']._serialized_end=215
  _globals['_AUDIOBRIDGE']._serialized_start=217
  _globals['_AUDIOBRIDGE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
