networks:
  speech:
    external: true

services:

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    networks:
      - speech
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
      

    ports:
      - "9092:9092"
      - "9644:9644"   # admin API (optional)

  minio:

    image: minio/minio:latest
    container_name: minio

    command: server /data --console-address ":9001"
    networks:
      - speech
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

  worker:
    platform: linux/amd64
    volumes:
      - ./storage_worker:/app/storage_worker
      - ./proto:/app/proto
    build:
      context: .
      dockerfile: storage_worker/Dockerfile

    container_name: storage-worker
    networks:
      - speech
    depends_on:
      - redpanda
      - minio

    environment:
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: audio-sessions

      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      KAFKA_EVENTS_TOPIC: audio_events

      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 50051

    ports:
      - "50051:50051"
  
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "redpanda:9092"
    depends_on:
      - redpanda
    networks:
      - speech
  vad-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app/client
      # - ./proto:/app/proto
    container_name: vad-client
    networks:
      - speech
    depends_on:
      - worker

    environment:
      STORAGE_HOST: worker:50051
      PYTHONUNBUFFERED: 1

    ports:
      - "6000:6000"

  asr_worker:
    build:
      context: .
      dockerfile: asr_worker/Dockerfile

    container_name: asr_worker

    networks:
      - speech

    depends_on:
      - redpanda
      - worker   # опционально, если потом S3/события от storage важны
    volumes:
      - ./client:/app/client
      - ./asr_worker:/app/asr_worker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      KAFKA_TOPIC: audio_events

      PYTHONUNBUFFERED: 1

    restart: unless-stopped
volumes:
  minio_data:



