# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: output.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coutput.proto\x12\x06\x61sr.v4\"\xad\x02\n\x1bSpeechRecognitionHypothesis\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x1d\n\x15normalized_transcript\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x15\n\rstart_time_ms\x18\x04 \x01(\r\x12\x13\n\x0b\x65nd_time_ms\x18\x05 \x01(\r\x12;\n\x05words\x18\x06 \x03(\x0b\x32,.asr.v4.SpeechRecognitionHypothesis.WordInfo\x1aX\n\x08WordInfo\x12\x15\n\rstart_time_ms\x18\x01 \x01(\r\x12\x13\n\x0b\x65nd_time_ms\x18\x02 \x01(\r\x12\x0c\n\x04word\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02J\x04\x08\x07\x10\x08\"\xe1\x03\n!SpeakerGenderAgeEmotionPrediction\x12\x45\n\x06gender\x18\x01 \x01(\x0e\x32\x35.asr.v4.SpeakerGenderAgeEmotionPrediction.GenderClass\x12?\n\x03\x61ge\x18\x02 \x01(\x0e\x32\x32.asr.v4.SpeakerGenderAgeEmotionPrediction.AgeClass\x12N\n\x07\x65motion\x18\x03 \x01(\x0b\x32=.asr.v4.SpeakerGenderAgeEmotionPrediction.EmotionsRecognition\x1a\x66\n\x13\x45motionsRecognition\x12\x10\n\x08positive\x18\x01 \x01(\x02\x12\x0f\n\x07neutral\x18\x02 \x01(\x02\x12\x16\n\x0enegative_angry\x18\x03 \x01(\x02\x12\x14\n\x0cnegative_sad\x18\x04 \x01(\x02\"C\n\x0bGenderClass\x12\x10\n\x0cGENDER_UNDEF\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02\"7\n\x08\x41geClass\x12\r\n\tAGE_UNDEF\x10\x00\x12\r\n\tAGE_ADULT\x10\x01\x12\r\n\tAGE_CHILD\x10\x02\"\xb9\x01\n\x11VoiceActivityMark\x12\x42\n\tmark_type\x18\x01 \x01(\x0e\x32/.asr.v4.VoiceActivityMark.VoiceActivityMarkType\x12\x11\n\toffset_ms\x18\x02 \x01(\x04\"M\n\x15VoiceActivityMarkType\x12\x10\n\x0cVA_MARK_NONE\x10\x00\x12\x11\n\rVA_MARK_BEGIN\x10\x01\x12\x0f\n\x0bVA_MARK_END\x10\x02\"C\n\x14VoiceActivitySegment\x12+\n\x08va_marks\x18\x01 \x03(\x0b\x32\x19.asr.v4.VoiceActivityMarkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPEECHRECOGNITIONHYPOTHESIS']._serialized_start=25
  _globals['_SPEECHRECOGNITIONHYPOTHESIS']._serialized_end=326
  _globals['_SPEECHRECOGNITIONHYPOTHESIS_WORDINFO']._serialized_start=232
  _globals['_SPEECHRECOGNITIONHYPOTHESIS_WORDINFO']._serialized_end=320
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION']._serialized_start=329
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION']._serialized_end=810
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION_EMOTIONSRECOGNITION']._serialized_start=582
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION_EMOTIONSRECOGNITION']._serialized_end=684
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION_GENDERCLASS']._serialized_start=686
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION_GENDERCLASS']._serialized_end=753
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION_AGECLASS']._serialized_start=755
  _globals['_SPEAKERGENDERAGEEMOTIONPREDICTION_AGECLASS']._serialized_end=810
  _globals['_VOICEACTIVITYMARK']._serialized_start=813
  _globals['_VOICEACTIVITYMARK']._serialized_end=998
  _globals['_VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE']._serialized_start=921
  _globals['_VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE']._serialized_end=998
  _globals['_VOICEACTIVITYSEGMENT']._serialized_start=1000
  _globals['_VOICEACTIVITYSEGMENT']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
