# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: output.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='output.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0coutput.proto\"\xb2\x01\n\x11VoiceActivityMark\x12;\n\tmark_type\x18\x01 \x01(\x0e\x32(.VoiceActivityMark.VoiceActivityMarkType\x12\x11\n\toffset_ms\x18\x02 \x01(\x04\"M\n\x15VoiceActivityMarkType\x12\x10\n\x0cVA_MARK_NONE\x10\x00\x12\x11\n\rVA_MARK_BEGIN\x10\x01\x12\x0f\n\x0bVA_MARK_END\x10\x02\"0\n\x08Response\x12$\n\x08va_marks\x18\x01 \x03(\x0b\x32\x12.VoiceActivityMarkb\x06proto3')
)



_VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE = _descriptor.EnumDescriptor(
  name='VoiceActivityMarkType',
  full_name='VoiceActivityMark.VoiceActivityMarkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VA_MARK_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VA_MARK_BEGIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VA_MARK_END', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE)


_VOICEACTIVITYMARK = _descriptor.Descriptor(
  name='VoiceActivityMark',
  full_name='VoiceActivityMark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mark_type', full_name='VoiceActivityMark.mark_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset_ms', full_name='VoiceActivityMark.offset_ms', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=195,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='va_marks', full_name='Response.va_marks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=245,
)

_VOICEACTIVITYMARK.fields_by_name['mark_type'].enum_type = _VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE
_VOICEACTIVITYMARK_VOICEACTIVITYMARKTYPE.containing_type = _VOICEACTIVITYMARK
_RESPONSE.fields_by_name['va_marks'].message_type = _VOICEACTIVITYMARK
DESCRIPTOR.message_types_by_name['VoiceActivityMark'] = _VOICEACTIVITYMARK
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoiceActivityMark = _reflection.GeneratedProtocolMessageType('VoiceActivityMark', (_message.Message,), dict(
  DESCRIPTOR = _VOICEACTIVITYMARK,
  __module__ = 'output_pb2'
  # @@protoc_insertion_point(class_scope:VoiceActivityMark)
  ))
_sym_db.RegisterMessage(VoiceActivityMark)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'output_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
